export const ProjectList = [
  {
    id: 1,
    title: "HarryPotterDB",
    desk: "HarryPotter Db is a web-based system using the ViteReactJs (React.js, Node.js). It simplifies web creation, images, and exploration with a user-friendly API's interface ",
    link: "https://final-hp.vercel.app/",
    imgLink: "/projects/hpdb.png",
    color: "#4D99BC",
  },
  {
    id: 2,
    title: "You Are Beautiful",
    desk: "Platform for students to express thoughts and ideas of searching every images.",
    link: "https://afritz-tech.github.io/ACTIVITY.PP3/",
    imgLink: "/projects/pp3.png",
    color: "#EDA208",
  },
  {
    id: 3,
    title: "Quotes",
    desk: " typically refers to a detailed explanation or context given about a quote. This could include: Source, Meaning, Context and Impact.",
    link: "https://afritz-tech.github.io/quotes.../",
    imgLink: "/projects/qts.png",
    color: "#435E39",
  },
  {
    id: 4,
    title: "X-MEN",
    desk: "the team is centered around individuals who possess extraordinary abilities due to mutations in their genetic code, making them a distinct branch of humanity called mutants.",
    link: "https://afritz-tech.github.io/XMEN-/",
    imgLink: "/projects/xmen.png",
    color: "#1E203C",
  },
  {
    id: 5,
    title: "PP2 Static Portfolio",
    desk: " Is a type of portfolio website that is built using fixed content and does not require server-side processing or dynamic updates. It is often designed to showcase personal, professional, or creative work in a simple, fast, and efficient way. ",
    link: "https://afritz-tech.github.io/ACTIVITY.-PORTFOLIO-PP2/",
    imgLink: "/projects/pp2.png",
    color: "#A69988",
  },
  {
    id: 6,
    title: "PP1 static Portfolio",
    desk: "Represents simple and creative way of building static portfolio website.",
    link: "https://afritz-tech.github.io/ACTIVITY.PP1/",
    imgLink: "/projects/pp1.png",
    color: "#23358D",
  },
];
